const MESSAGE_BODY_RICH_TEXT_BASE_SEGMENTS = [
  "message-body",
  "min-w-0",
  "max-w-full",
  "break-words",
  "[&_a]:text-accent",
  "[&_a]:underline",
  "hover:[&_a]:opacity-90",
  "[&_img]:my-1",
  "[&_img]:h-auto",
  "[&_img]:max-w-full",
  "[&_img]:rounded",
  "[&_ol]:my-1",
  "[&_ol]:list-decimal",
  "[&_ol]:list-outside",
  "[&_ol]:pl-5",
  "[&_ul]:my-1",
  "[&_ul]:list-disc",
  "[&_ul]:list-outside",
  "[&_ul]:pl-5",
  "[&_li]:my-0.5",
  "[&_li>p]:mb-0",
  "[&_p+ol]:mt-1",
  "[&_p+ul]:mt-1",
  "[&_ol+p]:mt-1",
  "[&_ul+p]:mt-1",
  "[&_p:last-child]:mb-0",
  "[&_p]:mb-1",
  "[&_pre]:my-1",
  "[&_pre]:min-w-0",
  "[&_pre]:max-w-full",
  "[&_pre]:whitespace-pre-wrap",
  "[&_pre]:border-l-2",
  "[&_pre]:border-border-subtle",
  "[&_pre]:py-2",
  "[&_pre]:pl-2",
  "[&_pre]:pr-2",
  "[&_pre]:font-mono",
  "[&_pre]:text-sm",
  "[&_pre]:italic",
  "[&_pre]:text-text-muted",
  "[&_pre]:[overflow-wrap:anywhere]",
  "[&_pre_code]:min-w-0",
  "[&_pre_code]:max-w-full",
  "[&_pre_code]:whitespace-pre-wrap",
  "[&_pre_code]:[overflow-wrap:anywhere]",
  "[&_span.user-mention]:text-accent",
  "hover:[&_span.user-mention]:opacity-90",
  "[&_table]:my-2",
  "[&_table]:w-full",
  "[&_table]:border-collapse",
  "[&_table]:text-sm",
  "[&_td]:border",
  "[&_td]:border-border-subtle",
  "[&_td]:px-2",
  "[&_td]:py-1",
  "[&_th]:border",
  "[&_th]:border-border-subtle",
  "[&_th]:px-2",
  "[&_th]:py-1",
  "[&_th]:text-left",
] as const;

export const MESSAGE_BODY_RICH_TEXT_BASE_CLASS_NAME =
  MESSAGE_BODY_RICH_TEXT_BASE_SEGMENTS.join(" ");

/** Applied to protected inline image previews in message bubbles (fixed 240×160 box). */
export const MESSAGE_MEDIA_PREVIEW_CLASS_NAME = "message-media-preview";

export const MESSAGE_BUBBLE_BODY_CLASS_NAME = [
  MESSAGE_BODY_RICH_TEXT_BASE_CLASS_NAME,
  "select-text",
  "[&_img:not(.message-media-preview)]:max-h-[160px]",
  "[&_img:not(.message-media-preview)]:w-auto",
  "[&_img:not(.message-media-preview)]:object-contain",
  "[&_img.message-media-preview]:block",
  "[&_img.message-media-preview]:h-40",
  "[&_img.message-media-preview]:w-60",
  "[&_img.message-media-preview]:max-w-full",
  "[&_img.message-media-preview]:cursor-pointer",
  "[&_img.message-media-preview]:object-contain",
  "[&_img.message-media-preview]:object-center",
  "[&_span.user-mention]:cursor-pointer",
].join(" ");

export const MESSAGE_COMPOSER_PREVIEW_BODY_CLASS_NAME = [
  "composer-preview-html",
  MESSAGE_BODY_RICH_TEXT_BASE_CLASS_NAME,
].join(" ");
