version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      development:
        dependency-type: development
        update-types: [minor, patch]
      production:
        dependency-type: production
        update-types: [patch]
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /packages/electron
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - electron

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - ci
